/**
 * The grounded corpus for "Ask the Historian".
 *
 * Every passage is written in plain words from general historical knowledge and
 * carries a plain-language `source` label — the kind of record the claim rests
 * on, not a fabricated page/ISBN citation. Passages deliberately model
 * uncertainty where the record is thin (e.g. the "burned for months" tradition).
 *
 * `nodes` link a passage to knowledge-graph node ids so a citation can light the
 * graph. `keywords` feed the offline retrieval scorer.
 */

export type Passage = {
  id: string;
  title: string;
  text: string;
  source: string;
  keywords: string[];
  nodes: string[];
};

export const PASSAGES: Passage[] = [
  {
    id: "founding",
    title: "A foundation under the Guptas",
    text: "Nalanda's great monastery was established in the 5th century CE, in the reign of the Gupta emperor Kumaragupta I, on land in Magadha long associated with the Buddha and his disciple Sariputra. Later Gupta and post-Gupta rulers added monasteries and shrines, so the site grew by accretion over centuries rather than to a single plan.",
    source: "Archaeological Survey of India excavation reports; Gupta-period inscriptions and seals from the site",
    keywords: ["founded", "founding", "origin", "gupta", "kumaragupta", "5th century", "who built", "when", "history", "began", "start", "established"],
    nodes: ["nalanda", "guptas", "kumaragupta", "magadha", "sariputra-stupa"],
  },
  {
    id: "mahavihara-meaning",
    title: "What 'mahavihara' means",
    text: "Nalanda was a mahavihara — a 'great monastery' that functioned as a residential university. Students lived on site for years, admitted only after debating a gatekeeper-scholar at the entrance, and followed a shared timetable of lectures, recitation and disputation.",
    source: "Yijing's account of Buddhist monastic practice in India, c. 690 CE",
    keywords: ["mahavihara", "meaning", "university", "monastery", "residential", "what is nalanda", "what was nalanda", "admission", "gate", "debate", "entrance"],
    nodes: ["nalanda", "yijing"],
  },
  {
    id: "scale",
    title: "The scale of the place",
    text: "Chinese pilgrims describe thousands of resident monks and students at Nalanda's height, drawn from across India and from Tibet, China, Korea, Sri Lanka and Southeast Asia. Numbers in the sources are impressions rather than censuses, but every visitor agrees the community was very large and its debates famous.",
    source: "Xuanzang's Great Tang Records on the Western Regions, 7th century CE; Yijing, c. 690 CE",
    keywords: ["how many", "students", "monks", "size", "population", "thousands", "big", "large", "scale", "foreign", "international"],
    nodes: ["nalanda", "xuanzang", "yijing"],
  },
  {
    id: "geography",
    title: "Where it stood",
    text: "The monastery lay in Magadha, in what is now Bihar, a short distance from the old capital of Pataliputra and from Rajgir, and within reach of Bodh Gaya. Its excavated ruins show long rows of monastic residences facing shrines across a central avenue, all built in fired red brick.",
    source: "Archaeological Survey of India site surveys at Nalanda, Bihar",
    keywords: ["where", "location", "bihar", "magadha", "pataliputra", "rajgir", "bodh gaya", "geography", "place", "situated", "brick", "ruins", "layout"],
    nodes: ["nalanda", "magadha", "pataliputra", "rajgir", "bodh-gaya"],
  },
  {
    id: "curriculum-overview",
    title: "What was taught",
    text: "Teaching ranged well beyond Buddhist doctrine. Alongside the Mahayana schools, students studied logic, Sanskrit grammar, medicine, mathematics and astronomy, the Vedas, and rival philosophical systems — the last so that a monk could argue against them in public debate.",
    source: "Xuanzang's Great Tang Records, 7th century CE; Yijing, c. 690 CE",
    keywords: ["curriculum", "subjects", "taught", "study", "studied", "courses", "learn", "logic", "grammar", "medicine", "astronomy", "mathematics", "vedas", "what did they teach"],
    nodes: ["nalanda", "hetuvidya", "shabdavidya", "chikitsavidya", "yogachara", "madhyamaka"],
  },
  {
    id: "logic",
    title: "The science of reasons",
    text: "Nalanda was a centre for hetuvidya, the 'science of reasons' — formal logic and epistemology. The tradition of Dignaga and later Dharmakirti, refined here, set the rules of valid inference and debate that Indian and Tibetan philosophy used for centuries.",
    source: "Surviving Sanskrit and Tibetan treatises on pramana (valid cognition); Xuanzang's record of the teachers he met",
    keywords: ["logic", "hetuvidya", "reason", "inference", "epistemology", "debate", "dignaga", "dharmakirti", "pramana", "argument"],
    nodes: ["hetuvidya", "dignaga", "dharmakirti", "nalanda", "pramanavarttika"],
  },
  {
    id: "medicine",
    title: "The healer's training",
    text: "Chikitsavidya, the study of medicine, was one of the five 'sciences' a learned monk was expected to know. It drew on the Ayurvedic tradition of Charaka and Sushruta — diagnosis, drugs compounded from plants and minerals, and surgery — and monks often served as physicians to the lay community around the monastery.",
    source: "Yijing's account, c. 690 CE, which describes Indian medical learning at length; the classical Ayurvedic compendia",
    keywords: ["medicine", "medical", "healer", "physician", "chikitsavidya", "ayurveda", "charaka", "sushruta", "healing", "doctor", "surgery", "drugs", "treatise"],
    nodes: ["chikitsavidya", "nalanda"],
  },
  {
    id: "grammar",
    title: "The gate of grammar",
    text: "Shabdavidya — the study of language — meant mastering Panini's Sanskrit grammar and its commentaries before almost anything else. Yijing reports that boys began this training young, because no scripture could be read closely without it.",
    source: "Yijing's account of the Indian curriculum, c. 690 CE",
    keywords: ["grammar", "language", "sanskrit", "panini", "shabdavidya", "philology", "words", "study of language"],
    nodes: ["shabdavidya", "nalanda"],
  },
  {
    id: "dharmaganja",
    title: "The Dharmaganja — the library quarter",
    text: "Tibetan tradition names Nalanda's library the Dharmaganja, the 'Treasury of the Dharma', and describes it as three buildings: Ratnasagara, Ratnodadhi and Ratnaranjaka. Ratnodadhi is remembered as nine storeys tall. No trace of these buildings has been securely identified in the excavated area, so their scale rests on written memory.",
    source: "Tibetan historical accounts, including Taranatha's History of Buddhism in India, 17th century",
    keywords: ["library", "dharmaganja", "books", "manuscripts", "ratnodadhi", "ratnasagara", "ratnaranjaka", "nine storeys", "three buildings", "collection", "archive", "treasury"],
    nodes: ["dharmaganja", "ratnodadhi", "taranatha", "nalanda"],
  },
  {
    id: "manuscript-materials",
    title: "What a book was made of",
    text: "A manuscript here was a bundle of dried, trimmed palm leaves, written with a stylus or reed pen in iron-gall or lamp-black ink, the leaves strung through one or two holes and pressed between wooden boards. Palm leaf lasts perhaps a few centuries in the Indian climate, so texts survived only by being copied again and again.",
    source: "Surviving Indian palm-leaf manuscripts and the codicological study of them",
    keywords: ["palm leaf", "manuscript", "book", "material", "made of", "ink", "stylus", "copy", "copying", "birch", "how were books made", "writing"],
    nodes: ["palm-leaf", "dharmaganja"],
  },
  {
    id: "prajnaparamita-mss",
    title: "The illuminated Prajnaparamita",
    text: "Among the finest books associated with Nalanda and its region are illuminated copies of the Ashtasahasrika Prajnaparamita, the 'Perfection of Wisdom in Eight Thousand Lines', with small painted panels of deities and scenes. Several survive in collections today, some carrying dates from the 11th and 12th centuries.",
    source: "Surviving dated Ashtasahasrika Prajnaparamita manuscripts in museum and monastery collections",
    keywords: ["prajnaparamita", "ashtasahasrika", "perfection of wisdom", "illuminated", "painted", "manuscript survive", "famous book", "eight thousand"],
    nodes: ["prajnaparamita", "ashtasahasrika", "palm-leaf"],
  },
  {
    id: "abhidharmakosha",
    title: "The Abhidharmakosha",
    text: "Vasubandhu's Abhidharmakosha, a systematic verse summary of Buddhist psychology and cosmology with the author's own prose commentary, was a core teaching text at Nalanda. Silabhadra's lineage taught it, and Xuanzang carried its teaching back to China.",
    source: "Xuanzang's biography and the transmission history of the text in Chinese and Tibetan",
    keywords: ["abhidharmakosha", "vasubandhu", "abhidharma", "textbook", "core text", "psychology", "cosmology"],
    nodes: ["abhidharmakosha", "silabhadra", "xuanzang"],
  },
  {
    id: "xuanzang",
    title: "Xuanzang, the pilgrim who stayed",
    text: "The Chinese monk Xuanzang reached Nalanda around 635 CE and remained for several years, studying Yogachara philosophy under the aged abbot Silabhadra. His travel record is the single richest description we have of the monastery in use — its towers, its teachers, its daily disputations.",
    source: "Xuanzang's Great Tang Records on the Western Regions, and the biography written by his disciple Huili",
    keywords: ["xuanzang", "hiuen tsang", "hsuan tsang", "chinese pilgrim", "chinese monk", "traveller", "635", "silabhadra", "yogachara", "who was xuanzang", "visitor"],
    nodes: ["xuanzang", "silabhadra", "yogachara", "nalanda", "chang-an"],
  },
  {
    id: "xuanzang-return",
    title: "Six hundred and fifty-seven texts",
    text: "When Xuanzang returned to China he is said to have carried some 657 Buddhist texts, transported by pack animals along the overland route through Central Asia. He spent the rest of his life in Chang'an translating them, and the Yogachara teaching of Nalanda took root in East Asia through that work.",
    source: "Xuanzang's biography by Huili; the catalogues of his translation output at Chang'an",
    keywords: ["657", "texts", "carried", "took back", "china", "translation", "chang'an", "return", "pack animals", "how did texts survive", "transmission", "central asia", "silk road"],
    nodes: ["xuanzang", "chang-an", "silk-road", "yogachara"],
  },
  {
    id: "yijing",
    title: "Yijing and the daily round",
    text: "The monk Yijing studied at Nalanda in the 670s and 680s and wrote a careful account of monastic life there: the water clock that timed the day, the bathing tanks, the rules for robes and meals, the seals that admitted a monk to the refectory. He travelled out by the sea route through the Bengal port of Tamralipti.",
    source: "Yijing's Record of Buddhist Practices Sent Home from the Southern Seas, c. 690 CE",
    keywords: ["yijing", "i-tsing", "yi jing", "daily life", "monastic life", "routine", "water clock", "seals", "meals", "robes", "tamralipti", "sea route", "who was yijing"],
    nodes: ["yijing", "tamralipti", "nalanda"],
  },
  {
    id: "silabhadra",
    title: "Silabhadra, the abbot",
    text: "Silabhadra headed Nalanda when Xuanzang arrived and was already very old. He was the leading authority on Yogachara — the 'mind-only' school — and it was his decision to teach the Yogacarabhumi to the Chinese visitor that shaped what returned to China.",
    source: "Xuanzang's biography by Huili",
    keywords: ["silabhadra", "abbot", "head", "teacher", "yogachara", "old", "who led nalanda", "principal"],
    nodes: ["silabhadra", "yogachara", "xuanzang", "nalanda"],
  },
  {
    id: "nagarjuna",
    title: "Nagarjuna and the Middle Way",
    text: "Later tradition places Nagarjuna, founder of the Madhyamaka or 'Middle Way' philosophy, among Nalanda's early figures, though he lived centuries before the monastery's documented peak. Whatever the truth of that link, Madhyamaka was taught and defended here throughout its history.",
    source: "Tibetan and Chinese hagiographical tradition; the teaching history of Madhyamaka texts",
    keywords: ["nagarjuna", "madhyamaka", "middle way", "emptiness", "shunyata", "philosophy", "founder"],
    nodes: ["nagarjuna", "madhyamaka", "nalanda"],
  },
  {
    id: "dignaga-dharmakirti",
    title: "The logicians",
    text: "Dignaga in the 5th–6th century and Dharmakirti in the 7th built the Buddhist theory of valid knowledge — perception and inference — into a rigorous system. Dharmakirti's Pramanavarttika became a text that every serious student at Nalanda, and later in Tibet, had to work through.",
    source: "Surviving Sanskrit fragments and complete Tibetan translations of the pramana treatises",
    keywords: ["dignaga", "dharmakirti", "logic", "pramanavarttika", "valid knowledge", "perception", "inference", "logician", "epistemology"],
    nodes: ["dignaga", "dharmakirti", "pramanavarttika", "hetuvidya"],
  },
  {
    id: "shantarakshita-tibet",
    title: "The road to Tibet",
    text: "In the 8th century the Nalanda scholar Shantarakshita travelled to Tibet at the invitation of its king, helped found the monastery of Samye, and began the systematic translation of Indian Buddhist texts into Tibetan. Much of what was lost in India later survived because of this transfer.",
    source: "Tibetan histories of the 'first diffusion' of Buddhism; the colophons of early Tibetan translations",
    keywords: ["shantarakshita", "tibet", "samye", "translation", "tibetan", "transmission", "8th century", "how did texts survive", "diffusion", "king"],
    nodes: ["shantarakshita", "tibet", "samye", "nalanda"],
  },
  {
    id: "atisha",
    title: "Atisha, the last great export",
    text: "Atisha Dipankara Srijnana, trained in the Nalanda tradition and connected to the nearby monastery of Vikramashila, left for Tibet in 1042 CE. His teaching reformed Tibetan Buddhism and is treated there as a direct inheritance from the Indian mahaviharas in their final century.",
    source: "Tibetan biographical tradition of Atisha; the records of the Kadam school he inspired",
    keywords: ["atisha", "dipankara", "vikramashila", "tibet", "1042", "kadam", "reform", "last teacher"],
    nodes: ["atisha", "vikramashila", "tibet"],
  },
  {
    id: "pala-patronage",
    title: "The Pala centuries",
    text: "From the 8th to the 12th century the Buddhist Pala dynasty of Bengal and Bihar were Nalanda's patrons, endowing it with revenue from villages and land. Kings such as Dharmapala and Devapala are named in inscriptions from the site as donors.",
    source: "Copperplate and stone inscriptions recovered at Nalanda naming Pala donors",
    keywords: ["pala", "patron", "patronage", "dharmapala", "devapala", "funding", "kings", "bengal", "endowment", "villages", "who paid", "support"],
    nodes: ["pala", "nalanda"],
  },
  {
    id: "harsha",
    title: "Harsha's gifts",
    text: "The emperor Harsha, who ruled much of north India in the early 7th century, is recorded by Xuanzang as a benefactor of Nalanda, assigning it the revenue of villages to feed and clothe its residents. Harsha also hosted the great debate assembly at Kanauj that Xuanzang attended.",
    source: "Xuanzang's Great Tang Records and his biography",
    keywords: ["harsha", "harshavardhana", "7th century", "emperor", "benefactor", "kanauj", "debate", "revenue", "villages"],
    nodes: ["harsha", "xuanzang", "nalanda"],
  },
  {
    id: "rival-mahaviharas",
    title: "Vikramashila and Odantapuri",
    text: "The Palas founded two more great monasteries nearby — Vikramashila and Odantapuri — partly to complement Nalanda and partly drawing scholars and patronage toward newer centres. By 1200 the mahaviharas of the Ganges plain formed a single connected world of teachers moving between them.",
    source: "Tibetan histories; Pala inscriptions; the shared teacher-lineages recorded in Tibetan translation colophons",
    keywords: ["vikramashila", "odantapuri", "rival", "other monasteries", "pala foundations", "network", "decline", "competition"],
    nodes: ["vikramashila", "odantapuri", "pala", "nalanda"],
  },
  {
    id: "nalanda-seal",
    title: "The monastery's own seal",
    text: "Excavators recovered clay sealings from the site stamped with a wheel flanked by two deer above the words Sri-Nalanda-Mahavihariya-Arya-Bhikshu-Sanghasya — 'of the community of noble monks of the illustrious Nalanda mahavihara'. It is the site telling us its own name.",
    source: "Terracotta sealings recovered in Archaeological Survey of India excavations at Nalanda",
    keywords: ["seal", "sealing", "name", "how do we know", "identify", "wheel", "deer", "sangha", "inscription", "proof"],
    nodes: ["nalanda-seal", "nalanda"],
  },
  {
    id: "architecture",
    title: "Brick viharas and shrines",
    text: "The excavated core is a line of nearly identical monasteries: a square of small cells around an open court, with a shrine on the wall facing the entrance, and opposite them a row of larger temples. Everything is fired brick, some walls still standing above head height, with traces of stucco figures and plaster.",
    source: "Archaeological Survey of India excavation reports for the Nalanda site",
    keywords: ["architecture", "buildings", "vihara", "cells", "courtyard", "shrine", "temple", "brick", "stucco", "what did it look like", "ruins", "layout"],
    nodes: ["nalanda", "sariputra-stupa"],
  },
  {
    id: "sariputra-stupa",
    title: "The great stupa of Sariputra",
    text: "The largest standing structure at the site is a stepped brick temple, rebuilt in seven phases over centuries, traditionally identified with the relics of the Buddha's disciple Sariputra, who tradition says was born and died in a village here. Its terraces still carry rows of stucco Buddha figures.",
    source: "Archaeological Survey of India survey of Temple Site 3 at Nalanda",
    keywords: ["stupa", "sariputra", "temple site 3", "biggest building", "relics", "disciple", "seven phases", "stucco"],
    nodes: ["sariputra-stupa", "nalanda"],
  },
  {
    id: "observatories",
    title: "Towers in the mist",
    text: "Xuanzang describes observatory towers at Nalanda that seemed to rise into the morning mist, and pavilions with pointed roofs. Nothing so tall survives; the description is one reason the nine-storey library of Tibetan memory is not dismissed outright.",
    source: "Xuanzang's Great Tang Records on the Western Regions, 7th century CE",
    keywords: ["towers", "observatory", "tall", "buildings", "mist", "height", "nine storeys", "xuanzang describes"],
    nodes: ["xuanzang", "nalanda", "dharmaganja"],
  },
  {
    id: "khalji-campaign",
    title: "Bakhtiyar Khalji in Magadha",
    text: "Around 1200 CE a Turkic commander in the service of the Ghurid conquest of north India, Ikhtiyar al-Din Muhammad Bakhtiyar Khalji, raided through Magadha and Bihar with a fast-moving cavalry force, taking fortified places and monasteries as he went before turning toward Bengal.",
    source: "Tabaqat-i-Nasiri, the Persian chronicle of Minhaj-i-Siraj, completed c. 1260 CE",
    keywords: ["bakhtiyar", "khalji", "khilji", "attack", "raid", "1200", "1202", "turkic", "ghurid", "invasion", "who destroyed", "cavalry", "bihar", "campaign", "conqueror"],
    nodes: ["bakhtiyar-khalji", "minhaj", "tabaqat", "magadha"],
  },
  {
    id: "tabaqat-account",
    title: "What the chronicle actually says",
    text: "Minhaj-i-Siraj, writing around 1260 from the report of a survivor he met, describes Bakhtiyar Khalji storming a fortified 'college' at a place called Bihar, its defenders shaven-headed men he took for a garrison. Inside, the chronicle says, were many books; when soldiers asked what the place was, the answer was that the word 'Bihar' itself meant a college.",
    source: "Tabaqat-i-Nasiri of Minhaj-i-Siraj, c. 1260 CE",
    keywords: ["tabaqat", "chronicle", "minhaj", "what does the source say", "bihar", "college", "shaven", "monks", "mistaken for a fort", "books", "primary source"],
    nodes: ["tabaqat", "minhaj", "bakhtiyar-khalji"],
  },
  {
    id: "burning-tradition",
    title: "Did the library burn for months?",
    text: "The often-repeated image of Nalanda's library burning for three months is not in the contemporary chronicle. It comes from later, mostly Tibetan, tradition. What the record and the archaeology together support is a violent sack around 1200, burnt layers in the ruins, and the collapse of the monastery as a working institution — not a documented timeline for the fire itself.",
    source: "Comparison of the c. 1260 Persian chronicle, later Tibetan histories, and modern archaeological findings",
    keywords: ["burned", "burnt", "fire", "three months", "months", "library burn", "myth", "tradition", "how long", "did it burn", "smoke", "destroyed by fire"],
    nodes: ["dharmaganja", "tabaqat", "taranatha"],
  },
  {
    id: "dharmasvamin",
    title: "A visitor in 1234",
    text: "The Tibetan monk Dharmasvamin came to Nalanda in 1234 CE, a generation after the sack. He found most of it deserted and damaged, soldiers still active in the area, but a few monastic buildings in use and one very old teacher — Rahula Sribhadra — still giving instruction to a small group of students.",
    source: "The biography of Dharmasvamin (Chag Lotsawa), based on his own account to a disciple",
    keywords: ["dharmasvamin", "1234", "after", "survivor", "aftermath", "ruined", "rahula sribhadra", "still teaching", "visited later", "what happened next", "chag lotsawa"],
    nodes: ["dharmasvamin", "rahula-sribhadra", "nalanda", "tibet"],
  },
  {
    id: "rahula-sribhadra",
    title: "The last teacher",
    text: "Rahula Sribhadra, the aged scholar Dharmasvamin met in 1234, is remembered as the last known head of teaching at Nalanda. When a local raid threatened, the story goes, he sent his students away to safety and refused to leave himself. With him the continuous life of the school is usually said to end.",
    source: "The biography of Dharmasvamin, 13th century",
    keywords: ["rahula sribhadra", "last teacher", "last scholar", "end", "final", "who was the last", "stayed behind", "1234"],
    nodes: ["rahula-sribhadra", "dharmasvamin", "nalanda"],
  },
  {
    id: "taranatha-survival",
    title: "Taranatha's memory of a partial revival",
    text: "Writing in Tibet in the 17th century, the historian Taranatha preserved a tradition that after the destruction a small number of monks returned and kept a reduced establishment going for a time, and that some manuscripts were carried to safety in Tibet and Nepal. His account is late and cannot be checked against contemporary records.",
    source: "Taranatha's History of Buddhism in India, 1608 CE",
    keywords: ["taranatha", "revival", "survived", "afterwards", "manuscripts saved", "carried to nepal", "carried to tibet", "returned", "partial", "rebuilt"],
    nodes: ["taranatha", "tibet", "nepal-route", "dharmaganja"],
  },
  {
    id: "excavation",
    title: "How the site was recovered",
    text: "The mounds at Nalanda were identified in the 1860s and excavated on a large scale through the first half of the 20th century, uncovering eleven monasteries and several temples in a north–south line, along with seals, sculpture, coins and burnt debris. Much of the site is still unexcavated.",
    source: "Archaeological Survey of India excavation history at Nalanda, Bihar",
    keywords: ["excavation", "dig", "archaeology", "discovered", "rediscovered", "1860s", "how do we know", "mounds", "ruins found", "asi"],
    nodes: ["nalanda", "nalanda-seal"],
  },
  {
    id: "route-uttarapatha",
    title: "The Uttarapatha",
    text: "The Uttarapatha, the great northern road, ran across the Ganges plain from Bengal toward the northwest, linking Nalanda's region to Mathura, Taxila and ultimately the passes into Central Asia. A manuscript sent west for safety would most likely start along it.",
    source: "Reconstruction of early historic trade routes from itineraries, inscriptions and the accounts of Chinese pilgrims",
    keywords: ["uttarapatha", "northern road", "route", "trade route", "west", "taxila", "mathura", "central asia", "which way", "send manuscript", "road"],
    nodes: ["uttarapatha", "nalanda", "silk-road"],
  },
  {
    id: "route-nepal-tibet",
    title: "The Nepal–Tibet passes",
    text: "The shortest way to Buddhist Tibet ran north through the Kathmandu Valley and over the Himalayan passes at Kyirong and Kuti. Tibetan monks used it constantly in both directions in Nalanda's last centuries, and it is the route later tradition credits with carrying manuscripts to safety.",
    source: "Colophons and travel accounts of Tibetan translators; later Tibetan historical tradition",
    keywords: ["nepal", "tibet", "route", "kathmandu", "himalaya", "passes", "kyirong", "kuti", "north", "send to tibet", "manuscripts saved", "safest"],
    nodes: ["nepal-route", "tibet", "nalanda"],
  },
  {
    id: "route-tamralipti",
    title: "The sea road from Tamralipti",
    text: "Tamralipti, a port on the Bengal coast near the mouth of the Ganges, was the usual place to take ship for Sri Lanka, Southeast Asia and, by stages, China. Both Xuanzang's later contemporaries and Yijing used it. In 1200 it lay in the direction Bakhtiyar Khalji was already moving.",
    source: "Yijing's account of his own voyages, c. 690 CE; the itineraries of Chinese pilgrims",
    keywords: ["tamralipti", "tamluk", "sea route", "port", "ship", "bengal", "sri lanka", "southeast asia", "by sea", "south", "voyage", "coast"],
    nodes: ["tamralipti", "yijing", "nalanda"],
  },
  {
    id: "route-silk-road",
    title: "The Silk Road to Chang'an",
    text: "Beyond the northwestern passes the routes joined the Silk Road through the oasis towns of the Tarim Basin — Kashgar, Khotan, Dunhuang — and on to the Chinese capital. This is the way Xuanzang's 657 texts travelled. It was long, crossed several kingdoms, and depended on the political weather of each.",
    source: "Xuanzang's own itinerary in the Great Tang Records; the archaeology of the Silk Road oasis sites",
    keywords: ["silk road", "china", "dunhuang", "kashgar", "khotan", "tarim", "chang'an", "oasis", "long route", "how xuanzang", "central asia"],
    nodes: ["silk-road", "chang-an", "xuanzang"],
  },
  {
    id: "debate-culture",
    title: "Won and lost by argument",
    text: "Public debate at Nalanda had real stakes: Xuanzang records that a scholar who lost a formal disputation might have to become the pupil of the winner, or leave. Visiting teachers challenged the monastery's champions, and the monastery sent its own to challenge others.",
    source: "Xuanzang's Great Tang Records and his biography by Huili",
    keywords: ["debate", "disputation", "argument", "contest", "stakes", "lost", "public", "challenge", "champion", "how debates worked"],
    nodes: ["nalanda", "hetuvidya", "xuanzang"],
  },
  {
    id: "what-was-lost",
    title: "What the loss actually was",
    text: "The lasting damage was not only burnt books but the end of a place where a large body of teachers passed a living tradition to the next generation face to face. Individual texts often survived elsewhere in copies; the institution that trained people to read and extend them did not.",
    source: "Modern historical assessment of the decline of organised Buddhist learning in eastern India",
    keywords: ["what was lost", "significance", "why does it matter", "impact", "meaning", "consequence", "tradition", "knowledge lost", "institution"],
    nodes: ["nalanda", "dharmaganja"],
  },
  {
    id: "yogachara",
    title: "Yogachara, the 'mind-only' school",
    text: "Yogachara analysed experience as a transformation of consciousness, arguing that the world as we grasp it is structured by mind. It was Silabhadra's speciality and, through Xuanzang, became one of the major philosophical schools of Chinese and later East Asian Buddhism.",
    source: "The Yogachara treatises preserved in Sanskrit, Chinese and Tibetan",
    keywords: ["yogachara", "mind only", "consciousness", "vijnanavada", "philosophy", "school", "silabhadra"],
    nodes: ["yogachara", "silabhadra", "xuanzang"],
  },
  {
    id: "madhyamaka",
    title: "Madhyamaka, the 'Middle Way'",
    text: "Madhyamaka holds that all things are empty of independent existence — they arise only in dependence on other things and on our concepts. Taught at Nalanda from Nagarjuna's lineage onward, it became, in Shantarakshita's synthesis, the framework carried to Tibet.",
    source: "The Madhyamaka treatises in Sanskrit and Tibetan; Shantarakshita's works",
    keywords: ["madhyamaka", "middle way", "emptiness", "shunyata", "dependent origination", "nagarjuna", "philosophy", "school"],
    nodes: ["madhyamaka", "nagarjuna", "shantarakshita"],
  },
  {
    id: "students-abroad",
    title: "Who came from abroad",
    text: "Names and origins of foreign students survive mostly by chance: Chinese monks in their own writings, Korean and Tibetan monks in translation colophons, a Sumatran prince in an inscription endowing a monastery at Nalanda in the 9th century. The monastery was a node in a network that stretched from Java to Chang'an.",
    source: "The Nalanda copperplate of Devapala recording a grant for a monastery built by a king of Srivijaya; pilgrim writings",
    keywords: ["foreign students", "abroad", "international", "korea", "china", "tibet", "srivijaya", "sumatra", "java", "who came", "network"],
    nodes: ["nalanda", "pala", "chang-an"],
  },
  {
    id: "why-decline-before",
    title: "Already thinner by 1200",
    text: "Nalanda in 1200 was not at its height. Patronage had spread to Vikramashila and Odantapuri and to Tibet itself; the Pala state that funded it was weak; Buddhism as a lay religion had contracted in eastern India. The raid struck an institution already reduced, which is part of why it did not recover.",
    source: "Modern historical scholarship on the decline of Buddhist institutions in early medieval eastern India",
    keywords: ["decline", "already", "before the attack", "weak", "why did it fall", "reduced", "patronage", "buddhism declining", "1200 state"],
    nodes: ["nalanda", "pala", "vikramashila", "odantapuri"],
  },
];

export const PASSAGE_BY_ID: Record<string, Passage> = Object.fromEntries(
  PASSAGES.map((p) => [p.id, p]),
);
